coverage:
  precision: 2
  round: down
  range: "30...100"
  status:
    project:
      default:
        enabled: yes
        target: 30%
    patch:
      default:
        enabled: yes
        target: 30%

comment:               
  layout: "reach, diff, flags, files"
  behavior: default
  require_changes: false  
  require_base: no        
  require_head: yes       
  branches:               
    - main
    - develop
